### ISSUE TITLE
忽略文件

### ISSUE THREAD

**Issue by Xi-Yuer** [itchaox/annotree#3]
建议可以根据用户目录下的.gitignore自动对所包含的文件进行忽略，也可自定义忽略文件以及对文件树结构的深度进行配置

**Comment by itchaox** [comment]
> 建议可以根据用户目录下的.gitignore自动对所包含的文件进行忽略，也可自定义忽略文件以及对文件树结构的深度进行配置

hi，好建议，感谢反馈~
1. 根据用户目录下的.gitignore自动对所包含的文件进行忽略（我记录下来，考虑下如何实现）
2. 自定义忽略文件（这个功能提供了的，只是细节我还需要再完善下）
3. 文件树结构的深度配置（这个是已经实现了，可以看下 READM 文档中的演示效果）

**Comment by DawnLck** [comment]
挺不错的！之前那个项目已经失去维护很久了，希望这个能一直活下去～

**Comment by itchaox** [comment]
> 挺不错的！之前那个项目已经失去维护很久了，希望这个能一直活下去～

非常感谢支持，后续我会一直维护，我还有很多功能想添加呢~，请继续关注哦！ 🥳

**Comment by itchaox** [comment]
@Xi-Yuer 感谢 pr，现在已支持自动根据 .gitignore 进行忽略
