### ISSUE TITLE
文本模式可否兼容Markdown

### ISSUE THREAD

**Issue by Atul-8** [itchaox/annotree#49]
佬, 我最近打算写一个库, 刚好想到你开发的这个软件, 很适合去做 库文件介绍;
但是我刚才发现 生成的文本模式 还得手动添加 ``` ``` 才能保持为目录树;

所以 希望可以把生成的格式直接附带 ``` ```

**Comment by itchaox** [comment]
> 佬, 我最近打算写一个库, 刚好想到你开发的这个软件, 很适合去做 库文件介绍; 但是我刚才发现 生成的文本模式 还得手动添加 ` ` 才能保持为目录树;
> 
> 所以 希望可以把生成的格式直接附带 ` `

Annotree 就是为了编写 Readme 文档而生的，嘿嘿~
感谢支持~

哈哈哈，英雄所见略同 https://github.com/itchaox/annotree/issues/31，这个问题我前几个月就想到啦，今天刚刚修复好，我过几天发一个版本

**Comment by itchaox** [comment]
> 佬, 我最近打算写一个库, 刚好想到你开发的这个软件, 很适合去做 库文件介绍; 但是我刚才发现 生成的文本模式 还得手动添加 ` ` 才能保持为目录树;
> 
> 所以 希望可以把生成的格式直接附带 ` `

效果如下
![20241113154216_rec_](https://github.com/user-attachments/assets/3f0a8ad9-2d14-4161-9bbf-a48fb2cae44d)
